import json

blogs_data = [
    {
        "id": 5,
        "title": "The Bathroom Door That Never Locked",
        "image": "https://images.unsplash.com/photo-1595844730298-b960fad97301?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
        "excerpt": "Why School Sanitation Is Still Failing Millions of Girls. For many girls, the hardest part of school is not mathematics, examinations, or homework. It is finding a toilet that feels safe...",
        "content": """Why School Sanitation Is Still Failing Millions of Girls\n\nFor many girls, the hardest part of school is not mathematics, examinations, or homework.\n\nIt is finding a toilet that feels safe.\n\nAcross low-income communities around the world, inadequate school sanitation quietly shapes the educational experiences of millions of menstruating students. A missing lock, a broken water tap, or the absence of a disposal bin may seem minor from the outside — but for a girl managing her period, these conditions can determine whether she attends school at all.\n\nIn countless schools, girls wait for hours to change a pad because there is no private space. Some avoid drinking water entirely to reduce the need to use the toilet. Others miss classes every month because the fear of staining their uniform feels unbearable.\n\nThe issue goes far beyond comfort.\n\nResearch consistently shows that poor WASH infrastructure — water, sanitation, and hygiene facilities — is directly linked to menstrual absenteeism. When schools lack clean toilets, running water, disposal systems, or privacy, girls are more likely to miss school during menstruation and more likely to disengage from classroom participation.\n\nAnd the burden is deeply unequal.\n\nIn many rural schools, boys can continue their day uninterrupted while girls navigate anxiety, discomfort, and shame in silence. The message becomes painfully clear: school systems were not designed with menstruating students in mind.\n\nBut infrastructure is not only about buildings.\n\nA functioning menstrual-friendly school environment includes:\n\nPrivate toilets with working locks\n\nAccess to clean water and soap\n\nDisposal bins for sanitary products\n\nEmergency menstrual supplies\n\nTeachers trained to respond without embarrassment\n\nPolicies that treat menstrual health as essential, not optional\n\nCountries that have invested in school sanitation alongside menstrual education are already seeing measurable results. Attendance improves. Confidence improves. Participation improves.\n\nBecause when girls no longer have to spend the school day worrying about where to change a pad, they gain the freedom to focus on learning.\n\nThe reality is simple:\n\nNo girl should have to choose between her education and her dignity.\n\nSchool toilets are not a side issue in menstrual health.\n\nThey are part of the foundation."""
    },
    {
        "id": 6,
        "title": "“Maybe It’s Normal”: Why So Many Girls Ignore Severe Period Pain",
        "image": "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
        "excerpt": "The Hidden Crisis of Undiagnosed Menstrual Disorders. When a young girl says her period pain is unbearable, the response she often hears is: 'Everyone goes through it'...",
        "content": """The Hidden Crisis of Undiagnosed Menstrual Disorders\n\nWhen a young girl says her period pain is unbearable, the response she often hears is:\n\n“Everyone goes through it.”\n\nFor generations, severe menstrual pain has been normalised to the point that millions of girls grow up believing suffering is simply part of being female.\n\nBut many of those girls are not experiencing “normal” periods.\n\nThey may be living with undiagnosed conditions such as endometriosis, polycystic ovary syndrome (PCOS), adenomyosis, or severe dysmenorrhea.\n\nThe problem is not only medical.\n\nIt is cultural.\n\nBecause menstruation is rarely discussed openly, many adolescents do not know what healthy menstrual symptoms actually look like. Pain that causes vomiting, fainting, school absence, or inability to function is often dismissed — by families, schools, and sometimes even healthcare systems.\n\nGlobally, studies show that conditions like endometriosis can take years to diagnose. During that time, girls may miss school regularly, experience declining mental health, and internalise the belief that their pain does not deserve attention.\n\nThe consequences accumulate quietly.\n\nA student who repeatedly misses classes due to severe pain may fall behind academically. A young woman who avoids seeking care because she fears embarrassment may continue suffering for years. In some cases, delayed diagnosis can affect fertility and long-term reproductive health.\n\nMenstrual pain should not automatically be treated as insignificant.\n\nOne of the most powerful public health interventions is simply teaching girls what is and is not normal.\n\nThat includes explaining:\n\nWhen cramps require medical attention\n\nSymptoms of common menstrual disorders\n\nThe importance of tracking cycles\n\nHow to seek reproductive healthcare safely\n\nThat debilitating pain is not something to silently endure\n\nTeachers, parents, and healthcare providers all play a role.\n\nThe earlier girls understand their bodies, the earlier they can advocate for their health.\n\nPeriods are normal.\n\nSevere suffering should not be."""
    },
    {
        "id": 7,
        "title": "The Mental Health Cost of Menstrual Shame",
        "image": "https://images.unsplash.com/photo-1493836512294-502baa1986e2?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
        "excerpt": "What Silence Does to Girls Over Time. Most conversations about menstruation focus on products, hygiene, or school attendance. Far fewer talk about the emotional burden...",
        "content": """What Silence Does to Girls Over Time\n\nMost conversations about menstruation focus on products, hygiene, or school attendance.\n\nFar fewer talk about the emotional burden.\n\nYet for many girls, menstruation becomes their first experience of shame connected to their own body.\n\nA whispered warning from an adult.\n\nA teacher skipping the reproductive health chapter.\n\nA classmate laughing at a visible stain.\n\nThese moments may appear small, but together they shape how girls understand themselves.\n\nPsychologists and adolescent health researchers increasingly recognise that menstrual stigma has measurable mental health effects. Girls who experience shame around menstruation report higher levels of anxiety, social withdrawal, embarrassment, and negative body image.\n\nFor some, the fear begins with menarche.\n\nGirls who receive no menstrual education before their first period often describe panic, confusion, or fear that something is seriously wrong. Without reassurance, those emotions can evolve into long-term discomfort discussing reproductive health.\n\nThe pressure to hide menstruation also creates chronic stress.\n\nMany girls constantly monitor their uniforms for stains, avoid participating in sports, or stay silent even when they need help. The emotional energy required to conceal a normal biological process can become exhausting.\n\nAnd because the topic remains taboo in many communities, girls often carry these anxieties alone.\n\nBreaking menstrual stigma is therefore not only a hygiene issue.\n\nIt is a mental health issue.\n\nCreating emotionally safe environments requires:\n\nOpen conversations at home\n\nAccurate school-based education\n\nTeachers who respond without shame\n\nMedia representation that normalises periods\n\nIncluding boys in menstrual education\n\nWhen girls learn that menstruation is healthy, ordinary, and nothing to hide, the psychological impact is profound.\n\nConfidence grows.\n\nParticipation grows.\n\nSelf-worth grows.\n\nSometimes the most important intervention is not a product or policy.\n\nIt is removing the shame."""
    },
    {
        "id": 8,
        "title": "Why Reusable Menstrual Products Are Changing Lives",
        "image": "https://images.unsplash.com/photo-1620302816999-5609e99aeb3e?ixlib=rb-4.0.3&auto=format&fit=crop&w=600&q=80",
        "excerpt": "The Growing Movement Beyond Disposable Pads. For decades, disposable sanitary pads have dominated conversations about menstrual health. But in many low-income and rural communities...",
        "content": """The Growing Movement Beyond Disposable Pads\n\nFor decades, disposable sanitary pads have dominated conversations about menstrual health.\n\nBut in many low-income and rural communities, they are not always the most practical solution.\n\nA packet of pads must be repurchased every month.\n\nSupply chains are often unreliable.\n\nWaste disposal systems may not exist.\n\nAnd for families already struggling financially, recurring product costs become impossible to sustain.\n\nThis is why reusable menstrual products are gaining global attention.\n\nReusable cloth pads and menstrual cups are increasingly being recognised not only as environmentally sustainable alternatives, but as long-term public health solutions.\n\nA single menstrual cup can last up to ten years.\n\nReusable cloth pads can dramatically reduce monthly costs.\n\nFor girls living in remote areas where shops rarely stock sanitary products, these options provide consistency and independence.\n\nBut successful implementation depends on more than distribution.\n\nEducation matters.\n\nGirls need clear information about:\n\nHow reusable products work\n\nCleaning and hygiene practices\n\nSafe storage\n\nCultural myths and misconceptions\n\nAccess to clean water and sanitation\n\nWithout education and infrastructure, even the best products can fail.\n\nCommunity acceptance also matters.\n\nIn some regions, misinformation around menstrual cups and virginity has slowed adoption. In others, girls fear ridicule if reusable products are visible while drying.\n\nThis is why menstrual health programmes work best when they combine products with conversation, community engagement, and trust-building.\n\nThe goal is not to promote one “perfect” menstrual product.\n\nThe goal is choice.\n\nEvery girl deserves access to a menstrual solution that is safe, affordable, dignified, and sustainable for her own environment.\n\nAnd for millions of women and girls worldwide, reusable products are becoming part of that future."""
    }
]

file_path = 'data/blog.json'
with open(file_path, 'r', encoding='utf-8') as f:
    existing_blogs = json.load(f)

existing_blogs.extend(blogs_data)

with open(file_path, 'w', encoding='utf-8') as f:
    json.dump(existing_blogs, f, indent=2, ensure_ascii=False)

print("Added successfully!")
